### ISSUE TITLE
SSH version of Git submodule could error out

### ISSUE THREAD

**Issue by kyletaylored** [natterstefan/speedtest-cron#1]
If you don't have an SSH key authenticated to your account, then you'll get a failure error.

```bash
pi@raspberrypi:~/speedtest-cron $ git submodule update --init
Submodule 'speedtest_cli' (git@github.com:sivel/speedtest-cli.git) registered for path 'speedtest_cli'
Cloning into '/home/pi/speedtest-cron/speedtest_cli'...
The authenticity of host 'github.com (192.30.253.112)' can't be established.
RSA key fingerprint is ---------------------------------.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.253.112' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:sivel/speedtest-cli.git' into submodule path '/home/pi/speedtest-cron/speedtest_cli' failed
```

Would suggest changing the git submodule path to HTTPS instead.

**Comment by kyletaylored** [comment]
Unfortunately since it's in `.git/config`, it's not something I can apply a PR to, but it would be this.

```bash
[submodule "speedtest_cli"]
        url = https://github.com/sivel/speedtest-cli
```

**Comment by natterstefan** [comment]
Hi @kyletaylored, thank you for the hint _and_ the research effort! Very helpful. Too bad we cannot do something about it (yet). I'll not close the issue yet so others see it too and (maybe) come up with a solution in the future.

**Comment by kyletaylored** [comment]
It looks like there's not really a solution to this, because it will always default to SSH when cloned. If you just search for ["github submodule http vs ssh"](https://www.google.com/search?q=github+submodule+http+vs+ssh), you will see a very lengthy list of issues regarding this.

I suppose the best solution would just be documenting the error in the README and how people can address it. For example, through Perl!

[One-liner to replace HTTPS into SSH url in .gitmodules](https://dhoeric.github.io/2017/https-to-ssh-in-gitmodules)
